name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Dependencies
      run : |
        sudo apt-get install libgtest-dev libcurl4-openssl-dev libfmt-dev libsnappy-dev protobuf-compiler libprotobuf-dev

    - name: Configure Cmake
      run: |
        cmake . -DBUILD_TESTS=ON

    - name: Run make
      run: |
        cmake --build .

    - name: Run Tests
      run: |
        ctest -V
